name = "JlCode"
uuid = "01063504-8e80-426a-8427-0f4d27a3bb86"
authors = ["AJB-ajb <al.busch@accc.de>"]
version = "0.1.0"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
AlgebraOfGraphics = "0.11.3"
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
CategoricalArrays = "0.10.8"
ColorSchemes = "3.29.0"
Colors = "0.13.1"
Crayons = "4.1.1"
DataFrames = "1.7.0"
Dates = "1.11.0"
Distributions = "0.25.122"
FastGaussQuadrature = "1.0.2"
Flux = "0.16.4"
ForwardDiff = "1.0.1"
Hyperopt = "0.5.6"
IntervalArithmetic = "0.22.36"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Measures = "0.3.2"
NonlinearSolve = "4.9.0"
Optim = "1.13.2"
Plots = "1.40.14"
Polynomials = "4.1.0"
PrettyTables = "2.4.0"
Printf = "1.11.0"
ProgressMeter = "1.10.4"
QuadGK = "2.11.2"
Random = "1.11.0"
ReverseDiff = "1.16.1"
Revise = "3.8.0"
Serialization = "1.11.0"
Statistics = "1.11.1"
StatsPlots = "0.15.7"
YAML = "0.4.14"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
